pkg install -y bash
pkg install -y bastille
pkg install -y cmake
pkg install -y git
pkg install -y gmp
pkg install -y mysql84-server
pkg install -y openjdk21
pkg install -y pkg
pkg install -y sudo
pkg install -y tmux
pkg install -y tomcat101
pkg install -y vim
