hostname="My"

ifconfig_em0="DHCP"
ifconfig_em0_ipv6="inet6 accept_rtadv"

sshd_enable="YES"
ntpd_enable="YES"
ntpd_sync_on_start="YES"
local_unbound_enable="YES"

powerd_enable="YES"
moused_enable="YES"
# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="AUTO"

tomcat101_enable="YES"
tomcat101_java_home="/usr/local/openjdk21"
mysql_enable="YES"

##   bastille_enable="YES"
##   cloned_interfaces="lo1"
##   gateway_enable="YES"
##   pf_enable="YES"
##   bastille_list="gitlab_jail"
